config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'welcome/index'

  get 'users/new'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:create, :new]
  resources :welcome

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get 'welcome/show'

  root to: "welcome#index"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, uniqueness: true

	def email=(value)
		value = value.strip.downcase
		write_attribute :email, value
	end
end

app/controllers/application_controller.rb
/media/faust/UUI/daiquiri_newclass ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?

  private

  def sign_in(user)
  	session[:user_id] = user.id if user.present?
  end

  def sign_out
  	session[:user_id] = nil
  end

  def user_logged_in!
    return if current_user?
    flash[:alert] = "Please sign to view this resource!"
    redirect_to login_url
  end

  def current_user
  	@current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def current_user?
    current_user.present?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by email: params[:email].downcase
		if user && user.authenticate(params[:password])	
			#sign in
			session[:user_id] = user.id
			flash[:notice] = "You are sign in!"
			redirect_to root_url
		else
			flash.now[:alert] = "Invalid user email or password"
			render "new"
		end	
	end

	def destroy
		sign_out
		flash[:notice] = "You are now signed out!"
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_param)

  	if @user.save
  		flash[:notice] = "You are now a user!"
  		sign_in @user #Method in controller
  		redirect_to root_url
  	else
  		render "new" 
  	end
  end


  private
  def user_param
  	params.require(:user).permit(
  		:email, :password, :password_confirmation
  	)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	user_logged_in!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
<% if current_user.present? %>
	Welcome <%= current_user.email %>
	<%= link_to "Sign out", logout_path %>
<% else %>
	<%= link_to "Register", new_user_path %>
	<%= link_to "Sign in", login_path %>
<% end %>
</p>

<p>
<%= notice %>
<%= alert %>
</p>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Registration:</h2>



<%= form_for @user do |f| %>
	<p>
		<%= f.label :email %>: <br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %>: <br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %>: <br>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.submit "Register" %>
	</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Index page</h1>
<p>Insert welcome text</p>



<ul>
	<% @users.each do |user| %>
		<%= user.email %>
		<br>
	<% end %>
</ul>

<%= link_to "auth", welcome_show_path %>

app/views/welcome/show.html.erb
<h2>Authenticated only:</h2>
<p>Private:
	Welcome: <%= current_user.email %> 
</p>